# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaymentExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PaymentExample
  pod 'Braintree'
  pod 'Stripe', '~> 14.0.0'
  # pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  target 'PaymentExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PaymentExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PaymentExample-tvOS

  target 'PaymentExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
