# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StripeExample' do
  pod 'Stripe', '~> 14.0.0'
  pod 'BraintreeDropIn', '~> 6.0'
  pod 'CardIO'
  inherit! :search_paths
end
