# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdmodExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AdmodExample
  platform :ios, '9.0'
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/AdMob', '~> 5.20.1'
  
  target 'AdmodExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AdmodExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AdmodExample-tvOS

  target 'AdmodExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
